try(require(shiny) || install.packages("shiny"))
try(require(udpipe) || install.packages("udpipe"))
try(require(shinyWidgets) || install.packages("shinyWidgets"))
try(require(igraph)|| install.packages("igraph"))
try(require(ggraph) || install.packages("ggraph"))
try(require(ggplot2) || install.packages("ggplot2"))
try(require(stringr) || install.packages("stringr"))

library(shinyWidgets)
library(shiny)
library(udpipe)
#library(textrank)
#library(lattice)
library(igraph)
library(ggraph)
library(ggplot2)
#library(wordcloud)
library(stringr)